export interface HardwareModel {
  name: string;
  brand: "NVIDIA" | "AMD" | "Intel" | "Apple" | "Dell" | "HP" | "Other";
  type: "gpu" | "cpu";
  releaseYear: number;
}

export const HARDWARE_LIST: HardwareModel[] = [
  // NVIDIA GPUs (Enterprise)
  { name: "NVIDIA H200 141GB", brand: "NVIDIA", type: "gpu", releaseYear: 2024 },
  { name: "NVIDIA H100 80GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA H800 80GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA A100 80GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA A100 40GB", brand: "NVIDIA", type: "gpu", releaseYear: 2020 },
  { name: "NVIDIA A800 80GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA L40S 48GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA L4 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA A6000 48GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX 6000 Ada 48GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA A10G 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA T4 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2018 },
  { name: "NVIDIA V100 32GB", brand: "NVIDIA", type: "gpu", releaseYear: 2017 },
  { name: "NVIDIA GH200 Grace Hopper Superchip", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX A5000 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX A4000 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX A2000 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA H100 NVL 94GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA L40 48GB", brand: "NVIDIA", type: "gpu", releaseYear: 2022 },
  { name: "NVIDIA K80 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2014 },

  // NVIDIA GPUs (Consumer/Workstation)
  { name: "NVIDIA RTX 4090 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2022 },
  { name: "NVIDIA RTX 4080 Super 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2024 },
  { name: "NVIDIA RTX 4080 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2022 },
  { name: "NVIDIA RTX 4070 Ti Super 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2024 },
  { name: "NVIDIA RTX 4070 Ti 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX 4070 Super 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2024 },
  { name: "NVIDIA RTX 4070 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX 4060 Ti 16GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX 4060 Ti 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX 4060 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2023 },
  { name: "NVIDIA RTX 3090 Ti 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2022 },
  { name: "NVIDIA RTX 3090 24GB", brand: "NVIDIA", type: "gpu", releaseYear: 2020 },
  { name: "NVIDIA RTX 3080 Ti 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX 3080 10GB", brand: "NVIDIA", type: "gpu", releaseYear: 2020 },
  { name: "NVIDIA RTX 3070 Ti 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX 3070 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2020 },
  { name: "NVIDIA RTX 3060 Ti 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2020 },
  { name: "NVIDIA RTX 3060 12GB", brand: "NVIDIA", type: "gpu", releaseYear: 2021 },
  { name: "NVIDIA RTX 2080 Ti 11GB", brand: "NVIDIA", type: "gpu", releaseYear: 2018 },
  { name: "NVIDIA RTX 2080 Super 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2019 },
  { name: "NVIDIA RTX 2070 Super 8GB", brand: "NVIDIA", type: "gpu", releaseYear: 2019 },
  { name: "NVIDIA GTX 1080 Ti 11GB", brand: "NVIDIA", type: "gpu", releaseYear: 2017 },

  // AMD GPUs
  { name: "AMD Instinct MI300X 192GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Instinct MI300A 128GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Instinct MI250X 128GB", brand: "AMD", type: "gpu", releaseYear: 2021 },
  { name: "AMD Instinct MI210 64GB", brand: "AMD", type: "gpu", releaseYear: 2022 },
  { name: "AMD Instinct MI100 32GB", brand: "AMD", type: "gpu", releaseYear: 2020 },
  { name: "AMD Radeon RX 7900 XTX 24GB", brand: "AMD", type: "gpu", releaseYear: 2022 },
  { name: "AMD Radeon RX 7900 XT 20GB", brand: "AMD", type: "gpu", releaseYear: 2022 },
  { name: "AMD Radeon RX 7900 GRE 16GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Radeon RX 7800 XT 16GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Radeon RX 7700 XT 12GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Radeon RX 7600 XT 16GB", brand: "AMD", type: "gpu", releaseYear: 2024 },
  { name: "AMD Radeon RX 7600 8GB", brand: "AMD", type: "gpu", releaseYear: 2023 },
  { name: "AMD Radeon RX 6950 XT 16GB", brand: "AMD", type: "gpu", releaseYear: 2022 },
  { name: "AMD Radeon RX 6900 XT 16GB", brand: "AMD", type: "gpu", releaseYear: 2020 },
  { name: "AMD Radeon RX 6800 XT 16GB", brand: "AMD", type: "gpu", releaseYear: 2020 },
  { name: "AMD Radeon RX 6800 16GB", brand: "AMD", type: "gpu", releaseYear: 2020 },
  { name: "AMD Radeon RX 6700 XT 12GB", brand: "AMD", type: "gpu", releaseYear: 2021 },
  { name: "AMD Radeon RX 6600 XT 8GB", brand: "AMD", type: "gpu", releaseYear: 2021 },

  // Intel GPUs
  { name: "Intel Data Center GPU Max 1550 (Ponte Vecchio)", brand: "Intel", type: "gpu", releaseYear: 2023 },
  { name: "Intel Data Center GPU Max 1100 48GB", brand: "Intel", type: "gpu", releaseYear: 2023 },
  { name: "Intel Data Center GPU Flex 170", brand: "Intel", type: "gpu", releaseYear: 2022 },
  { name: "Intel Data Center GPU Flex 140", brand: "Intel", type: "gpu", releaseYear: 2022 },
  { name: "Intel Arc A770 16GB", brand: "Intel", type: "gpu", releaseYear: 2022 },
  { name: "Intel Arc A750 8GB", brand: "Intel", type: "gpu", releaseYear: 2022 },
  { name: "Intel Arc A580 8GB", brand: "Intel", type: "gpu", releaseYear: 2023 },
  { name: "Intel Arc A380 6GB", brand: "Intel", type: "gpu", releaseYear: 2022 },

  // Apple GPUs
  { name: "Apple M4 Max GPU (40-Core)", brand: "Apple", type: "gpu", releaseYear: 2024 },
  { name: "Apple M4 Pro GPU (20-Core)", brand: "Apple", type: "gpu", releaseYear: 2024 },
  { name: "Apple M4 GPU (10-Core)", brand: "Apple", type: "gpu", releaseYear: 2024 },
  { name: "Apple M3 Ultra GPU (80-Core)", brand: "Apple", type: "gpu", releaseYear: 2024 },
  { name: "Apple M3 Max GPU (40-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M3 Pro GPU (18-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M3 GPU (10-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M2 Ultra GPU (76-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M2 Max GPU (38-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M2 Pro GPU (19-Core)", brand: "Apple", type: "gpu", releaseYear: 2023 },
  { name: "Apple M1 Ultra GPU (64-Core)", brand: "Apple", type: "gpu", releaseYear: 2022 },
  { name: "Apple M1 Max GPU (32-Core)", brand: "Apple", type: "gpu", releaseYear: 2021 },

  // AMD CPUs (Server & High-End Desktop)
  { name: "AMD EPYC 9754 (128-Core Bergamont)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD EPYC 9654 (96-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },
  { name: "AMD EPYC 9684X (96-Core Genoa-X)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD EPYC 9554 (64-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },
  { name: "AMD EPYC 9354 (32-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },
  { name: "AMD EPYC 8534PN (64-Core Siena)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD EPYC 7763 (64-Core)", brand: "AMD", type: "cpu", releaseYear: 2021 },
  { name: "AMD EPYC 7543 (32-Core)", brand: "AMD", type: "cpu", releaseYear: 2021 },
  { name: "AMD Ryzen Threadripper PRO 7995WX (96-Core)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD Ryzen Threadripper PRO 7975WX (32-Core)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD Ryzen Threadripper 3990X (64-Core)", brand: "AMD", type: "cpu", releaseYear: 2020 },
  { name: "AMD Ryzen 9 7950X3D (16-Core)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD Ryzen 9 7950X (16-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },
  { name: "AMD Ryzen 9 7900X (12-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },
  { name: "AMD Ryzen 7 7800X3D (8-Core)", brand: "AMD", type: "cpu", releaseYear: 2023 },
  { name: "AMD Ryzen 9 5950X (16-Core)", brand: "AMD", type: "cpu", releaseYear: 2020 },
  { name: "AMD Ryzen 7 5800X3D (8-Core)", brand: "AMD", type: "cpu", releaseYear: 2022 },

  // Intel CPUs (Server & High-End Desktop)
  { name: "Intel Xeon Platinum 8592+ (64-Core Emerald Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon Platinum 8580 (60-Core Emerald Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon Platinum 8490H (60-Core Sapphire Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon Platinum 8380 (40-Core Ice Lake)", brand: "Intel", type: "cpu", releaseYear: 2021 },
  { name: "Intel Xeon Gold 6548Y (32-Core Emerald Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon Gold 6430 (32-Core Sapphire Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon Gold 6330 (28-Core Ice Lake)", brand: "Intel", type: "cpu", releaseYear: 2021 },
  { name: "Intel Xeon Silver 4514Y (16-Core Emerald Rapids)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Core i9-14900KS (24-Core)", brand: "Intel", type: "cpu", releaseYear: 2024 },
  { name: "Intel Core i9-14900K (24-Core)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Core i9-13900K (24-Core)", brand: "Intel", type: "cpu", releaseYear: 2022 },
  { name: "Intel Core i7-14700K (20-Core)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Core i7-13700K (16-Core)", brand: "Intel", type: "cpu", releaseYear: 2022 },
  { name: "Intel Core i5-14600K (14-Core)", brand: "Intel", type: "cpu", releaseYear: 2023 },
  { name: "Intel Xeon W9-3495X (56-Core Workstation)", brand: "Intel", type: "cpu", releaseYear: 2023 },

  // Apple CPUs
  { name: "Apple M4 Max (16-Core)", brand: "Apple", type: "cpu", releaseYear: 2024 },
  { name: "Apple M4 Pro (14-Core)", brand: "Apple", type: "cpu", releaseYear: 2024 },
  { name: "Apple M4 (10-Core)", brand: "Apple", type: "cpu", releaseYear: 2024 },
  { name: "Apple M3 Ultra (24-Core)", brand: "Apple", type: "cpu", releaseYear: 2024 },
  { name: "Apple M3 Max (16-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M3 Pro (12-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M3 (8-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M2 Ultra (24-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M2 Max (12-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M2 Pro (12-Core)", brand: "Apple", type: "cpu", releaseYear: 2023 },
  { name: "Apple M2 (8-Core)", brand: "Apple", type: "cpu", releaseYear: 2022 },
  { name: "Apple M1 Ultra (20-Core)", brand: "Apple", type: "cpu", releaseYear: 2022 },
  { name: "Apple M1 Max (10-Core)", brand: "Apple", type: "cpu", releaseYear: 2021 },

  // Enterprise Systems (Dell / HP Packages)
  { name: "Dell PowerEdge R760 Server (Dual Intel Xeon)", brand: "Dell", type: "cpu", releaseYear: 2023 },
  { name: "Dell PowerEdge R750 Server (Dual Intel Xeon)", brand: "Dell", type: "cpu", releaseYear: 2021 },
  { name: "Dell PowerEdge XE9680 (8x NVIDIA H100)", brand: "Dell", type: "gpu", releaseYear: 2023 },
  { name: "Dell PowerEdge XE8640 (4x NVIDIA H100)", brand: "Dell", type: "gpu", releaseYear: 2023 },
  { name: "Dell PowerEdge R660 Server (Dual Intel Xeon)", brand: "Dell", type: "cpu", releaseYear: 2023 },
  { name: "Dell PowerEdge T560 Tower Server (Intel Xeon)", brand: "Dell", type: "cpu", releaseYear: 2023 },
  { name: "Dell PowerEdge R740 Server (Dual Intel Xeon)", brand: "Dell", type: "cpu", releaseYear: 2017 },
  { name: "HP ProLiant DL380 Gen11 (Dual Intel Xeon)", brand: "HP", type: "cpu", releaseYear: 2023 },
  { name: "HP ProLiant DL385 Gen11 (Dual AMD EPYC)", brand: "HP", type: "cpu", releaseYear: 2022 },
  { name: "HP ProLiant DL360 Gen11 (Dual Intel Xeon)", brand: "HP", type: "cpu", releaseYear: 2023 },
  { name: "HP ProLiant ML350 Gen11 (Intel Xeon)", brand: "HP", type: "cpu", releaseYear: 2023 },
  { name: "HP ProLiant DL325 Gen11 (AMD EPYC)", brand: "HP", type: "cpu", releaseYear: 2023 },
  { name: "HPE Cray XD670 (8x NVIDIA H100)", brand: "HP", type: "gpu", releaseYear: 2023 }
];
